server:
  port: 8080
  servlet:
    context-path: /

spring:
  cloud:
    discovery: localhost:8848
  datasource:
    url: jdbc:mysql://localhost:3306/module
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 192.168.88.130
    port: 5672
    username: guest
    password: guest
    virtual-host: /

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  application:
    name: cloud-demo

mybatis:
  type-aliases-package: com.example.demo.entity
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    root: info
    com.example.demo: debug



