server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    nacos:
      discovery: localhost:8848
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
            '[/**]':
                allowedOrigins:
                  - "http://localhost:5173/"
                  - "http://127.0.0.1:5173/"
                allowedMethods:
                  - "GET"
                  - "POST"
                  - "PUT"
                  - "DELETE"
                  - "OPTIONS"
                allowedHeaders: "*"
                allowCredentials: true
      routes:
        - id: cloud-demo
          uri: http://localhost:8080
          predicates:
            - Path=/**
